### ISSUE TITLE
Migrate to eBird Taxonomy v2022

### ISSUE THREAD

**Issue by brohitbrose** [swimos/munin#4]

**Comment by brohitbrose** [comment]
Completed a while back, forgot to close.

**Comment by chaetura9** [comment]
It looks like your .csv is just a subset of 3 columns of the eBird tax .csv: 
col 1: SPECIES_CODE [string]
col 2: PRIMARY_COM_NAME [string]
col 3: TAXON_ORDER [posint]

Plus one final record "nonavian".
So that the right (g)awk program will generate one from the other.
Just now, I diffed 2021, 2022, and 2023 ebird taxa with the main-branch file munin/src/main/resources/ebird-taxa.csv, and it matches the 2021 ebird taxa. There are a handful of glitches in ediff maybe related to whitespace, I don't see why ediff flagged the lines, didn't look into these yet, but in 2022 and 2023 every TAXON_ORDER does not match (a few counts off) and there are substantive record differences.

So (1) I'm not sure you did complete the update to 2022.

(2) 2023 is out and 2024 is 1-2 months away. Would it be helpful if I wrote the (g)awk program and submitted a PR for 2023 on it? I haven't checked out anything about how the munin csv is being used, and specificially why taxon_order is in there at all, so there may be issues with the renumber of taxon_order in 2022 and 2023.

**Comment by brohitbrose** [comment]
Thanks for the due diligence--I ended up merging changes into a separate branch (the deprecate-eBird-client). That's actually the branch that's running right now (though I haven't pushed all the commits yet, since I'm working on a more proper Taxonomy processor instead of the [one hacky file](https://github.com/swimos/munin/blob/deprecate-ebird-client/src/main/java/filethesebirds/munin/digest/TaxResolve.java) that it currently is). This branch is consistent with 2023.

taxon_order won't really used by this project anymore, so it is no longer a concern. It does have value when the catalog itself becomes publicly available to optimize database queries (e.g. show me all hawks, or show all flycatchers that are not empids). This app will submit db queries with taxon_code so that migrations remain straightforward. The catalog will have a separate table that utilizes taxon_order. Every time there is an eBird update, the latter table will have to be updated accordingly; this ends up being easiest to accomplish just by rebuilding it from the taxon_code table. I initially thought that there was backwards compatibility with the eBird updates to taxon_ordinal but I was wrong; luckily taxon_code is mostly compatible.

**Comment by brohitbrose** [comment]
Oh, and I already do have scripts for translating/simplifying the raw taxonomies, but thank you for offering! I suppose I should commit those too at some point.

**Comment by chaetura9** [comment]
Thanks for the info! I thought I saw those other branches hadn't been touched in a long time, but I'm not a sophisiticated user of git.
